#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun May 10 20:22:31 2015

import wx
from AutoGuideFrame import AutoGuideFrame

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frameAutoGuide = AutoGuideFrame(None, -1, "")
    app.SetTopWindow(frameAutoGuide)
    frameAutoGuide.Show()
    frameAutoGuide.ShowFullScreen(True)
    app.MainLoop()
