# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Fri May 29 00:00:40 2015

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
BUTTON_BACK = 1000
BUTTON_NEXT = 1001
BUTTON_CANCEL = 1002
STATIC_MSG = 1003

DIALOG_SIZE = (200, 30)
# end wxGlade


class CalibDialog(wx.Dialog):
    __sizer = None
    def __init__(self, *args, **kwds):
        # begin wxGlade: CalibDialog.__init__
        kwds["style"] = wx.SYSTEM_MENU | wx.FULL_REPAINT_ON_RESIZE
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelMsg = wx.StaticText(self, STATIC_MSG, "Message", style=wx.ALIGN_CENTRE)
        self.buttonBack = wx.Button(self, BUTTON_BACK, "<")
        self.buttonNext = wx.Button(self, BUTTON_NEXT, ">")
        self.buttonCancel = wx.Button(self, BUTTON_CANCEL, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CalibDialog.__set_properties
        self.SetTitle("dialog_1")
        self.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.SetForegroundColour(wx.Colour(255, 255, 255))
        self.labelMsg.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.labelMsg.SetForegroundColour(wx.Colour(255, 255, 255))
        self.labelMsg.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Roboto"))
        self.buttonBack.SetMinSize((20, 30))
        self.buttonBack.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonBack.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonNext.SetMinSize((20, 30))
        self.buttonNext.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonNext.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonCancel.SetMinSize((50,30))
        self.buttonCancel.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonCancel.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonCancel.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Roboto"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CalibDialog.__do_layout
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.labelMsg, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_5.Add(self.buttonBack, 0, 0, 0)
        sizer_5.Add(self.buttonNext, 0, 0, 0)
        sizer_5.Add(self.buttonCancel, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_5)
        self.__sizer = sizer_5
        self.reFitSize()
        # end wxGlade
        
    def reFitSize(self):
        if self.__sizer == None:
            return
        self.__sizer.Fit(self)
        self.Layout()
        
        

# end of class CalibDialog
