# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sat Jun 13 19:09:46 2015

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class ResolutionSelectDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ResolutionSelectDialog.__init__
        kwds["style"] = wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.listBoxResolution = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE | wx.LB_ALWAYS_SB)
        self.bitmapButtonOK = wx.BitmapButton(self, -1, wx.Bitmap("check.png", wx.BITMAP_TYPE_ANY))
        self.bitmapButtonCancel = wx.BitmapButton(self, -1, wx.Bitmap("no.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ResolutionSelectDialog.__set_properties
        self.SetTitle("Resolution")
        self.SetSize((200, 200))
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.SetForegroundColour(wx.Colour(255, 255, 255))
        self.listBoxResolution.SetMinSize((190, 160))
        self.listBoxResolution.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.listBoxResolution.SetForegroundColour(wx.Colour(255, 255, 255))
        self.bitmapButtonOK.SetMinSize((90, 30))
        self.bitmapButtonOK.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.bitmapButtonOK.SetForegroundColour(wx.Colour(255, 255, 255))
        self.bitmapButtonCancel.SetMinSize((90, 30))
        self.bitmapButtonCancel.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.bitmapButtonCancel.SetForegroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ResolutionSelectDialog.__do_layout
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(self.listBoxResolution, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(self.bitmapButtonOK, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(self.bitmapButtonCancel, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_11.Add(sizer_13, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_11)
        self.Layout()
        # end wxGlade

# end of class ResolutionSelectDialog
