# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Thu Jun 18 08:29:28 2015

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
DIALOG_SIZE=(200, 40)
# end wxGlade


class V4L2Dialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: V4L2Dialog.__init__
        kwds["style"] = wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.sliderValue = wx.Slider(self, -1, 0, 0, 10, style=wx.SL_HORIZONTAL | wx.SL_AUTOTICKS | wx.SL_LABELS)
        self.auto = wx.CheckBox(self, -1, "Auto")
        self.buttonClose = wx.BitmapButton(self, -1, wx.Bitmap("check.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: V4L2Dialog.__set_properties
        self.SetTitle("V4L2Dialog")
        self.SetSize((200, 40))
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.SetForegroundColour(wx.Colour(255, 255, 255))
        self.sliderValue.SetBackgroundColour(wx.Colour(160, 160, 160))
        self.sliderValue.SetForegroundColour(wx.Colour(255, 255, 255))
        self.sliderValue.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Roboto"))
        self.auto.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.auto.SetForegroundColour(wx.Colour(255, 255, 255))
        self.auto.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Roboto"))
        self.buttonClose.SetMinSize((28, 28))
        self.buttonClose.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonClose.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonClose.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Roboto"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: V4L2Dialog.__do_layout
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17.Add(self.sliderValue, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_17.Add(self.auto, 0, wx.LEFT | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_17.Add(self.buttonClose, 0, wx.LEFT | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        self.SetSizer(sizer_17)
        self.Layout()
        # end wxGlade

# end of class V4L2Dialog
