# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun May 24 20:12:57 2015

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
BUTTON_UP = 1000
BUTTON_DOWN = 1001
BUTTON_LEFT = 1002
BUTTON_RIGHT = 1003
BUTTON_OK = 1004
BUTTON_ZOOMUP = 1005
BUTTON_ZOOMDOWN = 1006

DIALOG_SIZE = (90, 90)
# end wxGlade


class ZoomDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ZoomDialog.__init__
        kwds["style"] = wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.buttonUp = wx.Button(self, BUTTON_UP, "^")
        self.buttonLeft = wx.Button(self, BUTTON_LEFT, "<")
        self.bitmapButtonOK = wx.BitmapButton(self, BUTTON_OK, wx.Bitmap("check.png"))
        self.buttonRight = wx.Button(self, BUTTON_RIGHT, ">")
        self.bitmapButtonZoomDown = wx.BitmapButton(self, BUTTON_ZOOMDOWN, wx.Bitmap("zoom_minus.png"))
        self.buttonDown = wx.Button(self, BUTTON_DOWN, "v")
        self.bitmapButtonZoomUp = wx.BitmapButton(self, BUTTON_ZOOMUP, wx.Bitmap("zoom.png"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ZoomDialog.__set_properties
        self.SetTitle("dialog_1")
        self.SetSize((90, 90))
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.buttonUp.SetMinSize((30, 30))
        self.buttonUp.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonUp.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonLeft.SetMinSize((30, 30))
        self.buttonLeft.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonLeft.SetForegroundColour(wx.Colour(255, 255, 255))
        self.bitmapButtonOK.SetMinSize((30, 30))
        self.bitmapButtonOK.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.bitmapButtonOK.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonRight.SetMinSize((30, 30))
        self.buttonRight.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonRight.SetForegroundColour(wx.Colour(255, 255, 255))
        self.bitmapButtonZoomDown.SetMinSize((30, 30))
        self.bitmapButtonZoomDown.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.bitmapButtonZoomDown.SetForegroundColour(wx.Colour(255, 255, 255))
        self.buttonDown.SetMinSize((30, 30))
        self.buttonDown.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.buttonDown.SetForegroundColour(wx.Colour(255, 255, 255))
        self.bitmapButtonZoomUp.SetMinSize((30, 30))
        self.bitmapButtonZoomUp.SetBackgroundColour(wx.Colour(64, 64, 64))
        self.bitmapButtonZoomUp.SetForegroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ZoomDialog.__do_layout
        grid_sizer_2 = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_2.Add((30, 30), 0, 0, 0)
        grid_sizer_2.Add(self.buttonUp, 0, 0, 0)
        grid_sizer_2.Add((30, 30), 0, 0, 0)
        grid_sizer_2.Add(self.buttonLeft, 0, 0, 0)
        grid_sizer_2.Add(self.bitmapButtonOK, 0, 0, 0)
        grid_sizer_2.Add(self.buttonRight, 0, 0, 0)
        grid_sizer_2.Add(self.bitmapButtonZoomDown, 0, 0, 0)
        grid_sizer_2.Add(self.buttonDown, 0, 0, 0)
        grid_sizer_2.Add(self.bitmapButtonZoomUp, 0, 0, 0)
        self.SetSizer(grid_sizer_2)
        self.Layout()
        # end wxGlade

# end of class ZoomDialog
